Replaced input autofocus with useRef solution to avoid warnings.
Autofocus had caused this:
Error: The autoFocus prop should not be used, as it can reduce usability and accessibility for users.